### ISSUE TITLE
Fix links to other lessons and episodes

### ISSUE THREAD

**Issue by LimorPeer** [curating4reproducibility/curating4reproducibility.github.io#44]
## Description

Some links to other lessons or episodes return to the current page, for example: https://curating4reproducibility.org/cure-carpentry-03-assessing/index.html . 

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Paste the information here as shown by `npm run check`

**Comment by tlchristian** [comment]
Corrected on lesson repositories
